FROM nanaones/psycopg-test:0.0.2


CMD ["cd", "/home"]    
CMD ["git", "clone", "https://github.com/nanaones/psycopg-test-docker", "/home/"]    
CMD ["bash", "/home/psycopg-test-docker/start/start.sh"]