FROM nanaones/psycopg-test:0.0.2

ENV loop 1
ENV minconn 1
ENV _log_save_folder_path /logs/
ENV _log_type json
ENV CONFIGPATH /config/config.ini
ENV IS_STAND_ALONE true
ENV DBMS_ADDRESS localhost
ENV DBMS_PORT 5432

ADD ./start /run
ADD ./config  /config
CMD ["bash", "/run/start.sh"]